import type { Metadata } from "next";
import ChildrenWrapper from "./ChildrenWrapper";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <section>
      <ChildrenWrapper>{children}</ChildrenWrapper>;
    </section>
  );
}
