"use client";
import React, { useEffect, useRef, useState } from "react";
import Hero from "../components/hero";
import Container from "../../components/container";
import aboutus from "@/public/assets/images/about-us.png";
import Image from "next/image";
import { ArrowRight, Checkmark } from "@/public/assets/icons";
import { useTranslations } from "next-intl";

const page = () => {
  const t = useTranslations("About-us");

  const slider = useRef<HTMLDivElement>(null);
  const card = useRef<HTMLDivElement>(null);

  const slideLeft = () => {
    if (!slider.current) return;
    if (!card.current) return;

    slider.current.scrollBy({
      left: -(slider.current.scrollWidth / 3),
      behavior: "smooth",
    });
  };

  const slideRight = () => {
    if (!slider.current) return;
    if (!card.current) return;

    slider.current.scrollBy({
      left: slider.current.scrollWidth / 3,
      behavior: "smooth",
    });
  };

  const coreFeatures = [
    {
      name: t("4"),
      description: t("5"),
    },
    {
      name: t("6"),
      description: t("7"),
    },
  ];

  const solve = [
    {
      name: t("9"),
      description: t("10"),
    },
    {
      name: t("11"),
      description: t("12"),
    },
    {
      name: t("13"),
      description: t("14"),
    },
  ];

  const keynotes = [
    {
      name: t("16"),
      items: [t("17"), t("18"), t("19")],
    },
    {
      name: t("20"),
      items: [t("21"), t("22"), t("23")],
    },
    {
      name: t("24"),
      items: [t("25"), t("26"), t("27")],
    },
    // {
    //   name: "Referral Program",
    //   items: [
    //     "Income Share: 25% of all income generated by referred clients.",
    //     "No Active Service Requirement: Participation doesn't require active service.",
    //     "Immediate Earnings Access: After client invoice settlement.",
    //   ],
    // },
    // {
    //   name: "Customer Support and Education",
    //   items: [
    //     "Resources: Comprehensive frequently asked questions and educational materials.",
    //     "Support Team: Available via the app’s chat system and email.",
    //     "AI Assistance: A trained large language model (Ai) ready to answer service-related questions.",
    //   ],
    // },
    // {
    //   name: "Risk Management",
    //   items: [
    //     "Diversification: Across exchanges, strategies, and assets.",
    //     "Non-Custodial Approach: Minimizes counterparty risks.",
    //     "Sophisticated Tools: For risk assessment and management.",
    //   ],
    // },
  ];

  return (
    <div className="">
      <Hero title={t("0")} />
      <Container>
        <div className="w-full">
          <div className="mx-auto my-12 max-w-[803.18px] text-[#090909] text-base md:text-lg font-light">
            {t("1")}
            <br /> <br />
            {t("2")}
          </div>

          <div className="w-full mt-12 mb-24">
            <div className="text-center text-[#006fe3] text-[24px] md:text-[28px] xl:text-[32px] font-normal">
              {t("3")}
            </div>

            <div className="w-full flex flex-col md:flex-row items-center justify-center gap-10 mt-12">
              {coreFeatures.map((feature, index) => (
                <div
                  key={index}
                  className="w-full md:w-[480px] xl:w-[531px] h-[200px] md:h-[250px] xl:h-[277.88px] px-8 bg-[#e8f0f7] rounded-lg flex-col justify-center items-end inline-flex"
                >
                  <div className="self-stretch text-center">
                    <span className="text-[#090909] text-lg md:text-xl font-normal ">
                      {feature.name}
                      <br />
                    </span>
                    <span className="text-[#090909] text-lg md:text-2xl font-normal ">
                      <br />
                    </span>
                    <span className="text-[#090909] text-base md:text-lg font-normal ">
                      {feature.description}
                    </span>
                  </div>
                </div>
              ))}
            </div>
          </div>
        </div>
      </Container>
      <div className="h-auto bg-[#F4F6F8] w-full my-12 py-10  md:py-[100px]">
        <div className="text-center text-[#006fe3] text-[24px] md:text-[28px] xl:text-[32px]] font-normal">
          {t("8")}
        </div>

        <div className="w-full mt-12 flex flex-col lg:flex-row items-center justify-center gap-10 before:">
          <Image src={aboutus} className="w-[351.17px] h-[363px]" alt="" />
          <div className="w-full px-5 md:px-0 max-w-[591.80px] flex-col justify-start items-start gap-8 inline-flex">
            {solve.map((item, index) => (
              <div key={index} className="card self-stretch">
                <span className="name text-[#090909] text-lg font-semibold ">
                  {item.name}
                  <br />
                </span>
                <span className="text-[#090909] text-lg font-light ">
                  {item.description}
                </span>
              </div>
            ))}
          </div>
        </div>
      </div>
      <Container>
        <div className="w-full my-10 md:my-[100px] overflow-clip">
          <div className="w-full flex items-center justify-between mb-6">
            <div className="text-center text-[#006fe3] text-[24px] md:text-[28px] xl:text-[32px] font-normal ">
              {t("15")}
            </div>

            <div className="flex gap-3 text-[#006fe3]">
              <div
                onClick={slideLeft}
                className="px-2 py-1.5 bg-[#e8f0f7] rounded justify-start items-center gap-3 inline-flex cursor-pointer"
              >
                <ArrowRight className="w-6 h-6 rotate-180" />
              </div>
              <div
                onClick={slideRight}
                className="px-2 py-1.5 bg-[#e8f0f7] rounded justify-start items-center gap-3 inline-flex cursor-pointer"
              >
                <ArrowRight className="w-6 h-6 " />
              </div>
            </div>
          </div>

          <div
            ref={slider}
            id="slider"
            className="w-auto flex overflow-scroll gap-2 md:gap-4 xl:gap-8"
          >
            {keynotes.map((keynote, index) => (
              <div
                ref={card}
                key={index}
                className={`min-w-[385px] md:min-w-[420px] xl:min-w-[531px] p-8 rounded-lg border border-[#006fe3] flex-col justify-center items-end gap-2 inline-flex`}
              >
                <div className="self-stretch text-[#006fe3] text-base md:text-lg font-normal ">
                  {keynote.name}
                </div>
                {keynote.items.map((item, idx) => (
                  <div
                    key={idx}
                    className="self-stretch justify-center items-center gap-2 inline-flex"
                  >
                    <Checkmark className="w-6 h-6 text-[#006fe3]" />
                    <div className="grow shrink basis-0 text-[#090909] text-sm md:text-base xl:text-lg font-normal ">
                      {item}
                    </div>
                  </div>
                ))}
              </div>
            ))}
          </div>
        </div>
      </Container>
    </div>
  );
};

export default page;
